#!/usr/bin/env python

"""
Make.py GUI
"""
import sys
import re
from PyQt4.QtCore import *
from PyQt4.QtGui import *

class MainWindow(QMainWindow):

    def __init__(self, parent=None):
        super(MainWindow, self).__init__(parent)
        self.form_widget = FormWidget(self)
        self.setCentralWidget(self.form_widget)

class FormWidget(QWidget):
    def __init__(self, parent):
        super(FormWidget, self).__init__(parent)
        self.layout = QVBoxLayout(self)

        def populateList(self):
            with open(fname) as f:
                block = f.readlines()
            for line in block:
                self.block_list.addItem(line)

        def retrieve_blk_name(filename, linepattern, newline):
            """ Detects the re 'linepattern' in the file. After its last occurrence,
            stores line per line the contents of the file into a list. If the pattern
            does not exist, returns.
            """
            files = open(filename, 'r').read()
            lines = re.findall(linepattern, files, flags=re.MULTILINE)
            if len(lines) == 0:
                return

            oldfile = open(filename, 'r').read()
            lines = re.findall(newline, oldfile, flags=re.MULTILINE)
            if len(lines) != 0:
                pass
            else:
                pattern_lines = re.findall(linepattern, oldfile, flags=re.MULTILINE)
                if len(pattern_lines) == 0:
                    open(filename, 'a').write(newline)
                    return
                last_line = pattern_lines[-1]
                newfile = oldfile.replace(last_line, last_line + newline + '\n')
                open(filename, 'w').write(newfile)


# Create the action for the button
        @pyqtSlot()
        def on_click():
            print('clicked')
        @pyqtSlot()
        def on_press():
            print('pressed')
        @pyqtSlot()
        def on_release():
            print('released')
#Message box - No blocks found on given path
        @pyqtSlot()
        def loadList():
            # QMessageBox.warning(window, "No Blocks Found!", "No RFNoC blocks found in the given path.")
            populateList(self)


        self.btn = QPushButton('Do not press')
        self.layout.addWidget(self.btn)
        # Add buttons for file showing or bit generation
        # This buttons also execute the final command
        self.show_file_btn = QPushButton('Show instantiation File')
        self.show_file_btn.setToolTip('Click to open the resultant file in a new window')
        #show_file_btn.clicked.connect(exit)
        self.show_file_btn.resize(self.show_file_btn.sizeHint())
        self.layout.addWidget(self.show_file_btn)
        # self.show_file_btn.move(100, 80)
### /endlist
#Create textbox for RFNoC OOT Paths
        self.oot_path_label = QLabel
        self.oot_path = QLineEdit()
        self.oot_path.move(20,20)
        self.oot_path.resize(280,40)
        self.layout.addWidget(self.oot_path)
####
# Working on list widget
###
        self.block_list = QListWidget()
        self.block_list.addItem("Item 1")
        self.block_list.addItem("Item 2")
        self.block_list.addItem("Item 3")
        self.block_list.addItem("Item 4")
        self.layout.addWidget(self.block_list)


# Connect the signals to the slots
        self.show_file_btn.clicked.connect(on_click)
        self.show_file_btn.pressed.connect(on_press)
        self.show_file_btn.released.connect(on_release)
        self.btn.clicked.connect(loadList)
        fname = 'text1.scrs'

app = QApplication(sys.argv)
window = MainWindow()
window. resize(620, 440)
window. setWindowTitle("Make.py GUI")

window.show()
#sys.exit(a.exec_())
app.exec_()
