#!/usr/bin/env python
# from PyQt4.QtGui import *
# from PyQt4.QtCore import *

# import sys

# class myListWidget(QListWidget):

   # def Clicked(self,item):
      # QMessageBox.information(self, "ListWidget", "You clicked: "+item.text())

# def main():
   # app = QApplication(sys.argv)
   # listWidget = myListWidget()

   # #Resize width and height
   # listWidget.resize(300,120)

   # listWidget.addItem("Item 1");
   # listWidget.addItem("Item 2");
   # listWidget.addItem("Item 3");
   # listWidget.addItem("Item 4");

   # listWidget.setWindowTitle('PyQT QListwidget Demo')
   # listWidget.itemClicked.connect(listWidget.Clicked)

   # listWidget.show()
   # sys.exit(app.exec_())

# if __name__ == '__main__':
   # main()


from PyQt4.QtCore import *
from PyQt4.QtGui  import *

import sys

class MyMainWindow(QMainWindow):

    def __init__(self, parent=None):

        super(MyMainWindow, self).__init__(parent)
        self.form_widget = FormWidget(self)
        self.setCentralWidget(self.form_widget)


class FormWidget(QWidget):

    def __init__(self, parent):
        super(FormWidget, self).__init__(parent)
        self.layout = QVBoxLayout(self)

        self.button1 = QPushButton("Button 1")
        self.layout.addWidget(self.button1)

        self.button2 = QPushButton("Button 2")
        self.layout.addWidget(self.button2)

        self.setLayout(self.layout)

app = QApplication([])
foo = MyMainWindow()
foo.show()
sys.exit(app.exec_())
